
USE HEALTH_MANAGEMENT_SYSTEM;

CREATE DATABASE HEALTHY_SYSTEM;
USE HEALTHY_SYSTEM;

CREATE TABLE PATIENT(
  PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
  FIRSTNAME VARCHAR(100),
  GENDER VARCHAR(10),
  DATEOFBIRTH VARCHAR(100),
  ADDRESS VARCHAR(100),
  PHONE VARCHAR(20)
  
  );
  
 CREATE TABLE HEALTH_WORKER(
       WORK_ID INT PRIMARY KEY AUTO_INCREMENT,
       FIRSTNAME VARCHAR(100),
       LASTNAME VARCHAR(100),
       POSITION VARCHAR(100),
       PHONE VARCHAR(100)
       );
       
CREATE TABLE VISIT(
    VISIT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOW_DATE DATE,
    NOTES VARCHAR(100),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (WORK_ID) REFERENCES HEALTH_WORKER(WORK_ID)
    );
    
CREATE TABLE APPOINTMENT(
    APPOINTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    DATE_NOW DATE,
    TIMES TIME,
    FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
    
   );
   
CREATE TABLE DIAGNOSIS(
    DIAGNOSIS_ID INT PRIMARY KEY AUTO_INCREMENT,
    DIAGNOSISNAME VARCHAR(100),
    DESCRIPTION VARCHAR(100),
    FOREIGN KEY (VISIT_ID) REFERENCES VISIT(VISIT_ID)
    );
 
CREATE TABLE TREATMECREATE DATABASE HEALTHY_SYSTEMES;
USE HEALTHY_SYSTEMES;


CREATE TABLE PATIENT(
    PATIENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    GENDER VARCHAR(10),
    DATEOFBIRTH DATE, 
    ADDRESS VARCHAR(100),
    PHONE VARCHAR(20)
);
  

CREATE TABLE HEALTH_WORKER(
    WORK_ID INT PRIMARY KEY AUTO_INCREMENT,
    FIRSTNAME VARCHAR(100) NOT NULL,
    LASTNAME VARCHAR(100) NOT NULL,
    POSITION VARCHAR(100),
    PHONE VARCHAR(100)
);
       
CREATE TABLE VISIT(
    VISIT_ID INT PRIMARY KEY AUTO_INCREMENT,
    NOW_DATE DATE NOT NULL,
    NOTES VARCHAR(100),
    PATIENT_ID INT, 
    WORK_ID INT,   
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(PATIENT_ID),
    FOREIGN KEY (WORK_ID) REFERENCES HEALTH_WORKER(WORK_ID)
);
    

CREATE TABLE APPOINTMENT(
    APPOINTMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    DATE_NOW DATE NOT NULL,
    TIMES TIME NOT NULL,
    PATIENT_ID INT, 
    FOREIGN KEY(PATIENT_ID) REFERENCES PATIENT(PATIENT_ID)
);
   

CREATE TABLE DIAGNOSIS(
    DIAGNOSIS_ID INT PRIMARY KEY AUTO_INCREMENT,
    DIAGNOSISNAME VARCHAR(100) NOT NULL,
    DESCRIPTION VARCHAR(100),
    VISIT_ID INT, 
    FOREIGN KEY (VISIT_ID) REFERENCES VISIT(VISIT_ID)
);
 

CREATE TABLE TREATMENT(
    TREATMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_NAME VARCHAR(100) NOT NULL,
    MEDICATION VARCHAR(100),
    DOSAGE VARCHAR(100),
    DIAGNOSIS_ID INT,
    FOREIGN KEY(DIAGNOSIS_ID) REFERENCES DIAGNOSIS(DIAGNOSIS_ID)
);
NT(
    TREATMENT_ID INT PRIMARY KEY AUTO_INCREMENT,
    TREATMENT_NAME VARCHAR(100),
    MEDICATION VARCHAR(100),
    DOSAGE VARCHAR(100),
    FOREIGN KEY(DIAGNOSIS_ID) REFERENCES DIAGNOSIS(DIAGNOSIS_ID)
    );
    